FROM tomcat:9.0
#ADD /var/lib/docker/volumes/boxfuseindocker_boxfusevol/_data/hello-1.0.war /usr/local/tomcat/webapps/
#ADD hello-1.0.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]